name: Release

on:
  push:
   branches:    
    # Push events on main branch
   - dev-yanmi
   tags:
     - 'v*.*.*'

  
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14


      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          
      - name: Create Release
        run: echo ${{steps.get_version.name.outputs.VERSION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
